name: todoapp
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
 

  cupertino_icons: ^1.0.2
  flutter_keyboard_visibility: ^5.4.1
  page_transition: ^2.0.9
  hooks_riverpod: ^2.3.7
  shared_preferences: ^2.0.15
  flutter_screenutil: ^5.5.4
  logging: ^1.1.0
  google_fonts: ^5.1.0
  smooth_page_indicator: ^1.1.0
  # flutter_riverpod: ^2.3.1
  flutter_svg: ^1.1.4
  flutter_vector_icons: ^2.0.0
  intl_phone_field: ^3.1.0
  internet_connection_checker: ^0.0.1+2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  chopper: ^6.1.1
  otp_text_field: ^1.1.3




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: 
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  chopper_generator: ^6.0.0
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/